### ISSUE TITLE
No Hex to Dec conversion

### ISSUE THREAD

**Issue by IlyaKl** [ioBroker/ioBroker.rflink#3]
I connected to rifling a new sensor OWL MICRO+. The input Watt and kWatt data are not converted from hex to decimal 

P.S. ioBroker recognized the sensor as Oregon CM-180

**Comment by GermanBluefox** [comment]
If I look at 

> 20;88;Oregon CM180;ID=008F;WATT=0223;KWATT=000002d0;

What is the valid values? WATT = 223 or WATT = 547?

**Comment by IlyaKl** [comment]
Dear Bluefox,
Please, see the print screen attached
![2017-01-19 14 19 29](https://cloud.githubusercontent.com/assets/25218547/22108293/ba3f76da-de52-11e6-81da-b6540ee36bf4.png)

Regards,
Ilya

**Comment by GermanBluefox** [comment]
Fixed: 
https://github.com/ioBroker/ioBroker.rflink/commit/782ba0ce2a277198971e2608eb71de65256da6ce

**Comment by IlyaKl** [comment]
Dear Bluefox, you forgot to divide KWATT value by 1000 to get value in kilowatts. 

Regards,
Ilya

**Comment by GermanBluefox** [comment]
Done. Thank you.

2017-01-20 14:41 GMT+01:00 IlyaKl <notifications@github.com>:
